version: "3.4"
services:
  www:
    image: koromerzhin/django:4.0.2
    command: >
      sh -c "pip -install -r requirements.txt && python manage.py runserver 0.0.0.0:8080"
    volumes:
      - ${PWD}/apps:/app:delegated
    depends_on:
      - mariadb
      - mailhog
