version: "3.4"
networks:
  proxylampy:
    external: true
  serverlampy:
    external: true
  net:
    driver: overlay
    attachable: true

services:
  exec:
    image: koromerzhin/django:3.9.0
    volumes:
      - ${PWD}/apps:/app
    command: sh -c "pip -install -r requirements.txt"
    networks:
      - serverlampy
      - proxylampy
    depends_on:
      - mariadb
      - mailhog
    deploy:
      restart_policy:
        condition: none
      labels:
        - "traefik.enable=false"
  www:
    image: koromerzhin/django:3.9.0
    volumes:
      - ${PWD}/apps:/app
    networks:
      - serverlampy
      - proxylampy
    depends_on:
      - mariadb
      - mailhog
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.django.rule=HostRegexp(`django.traefik.me`, `django.{ip:.*}.traefik.me`)"
        - "traefik.http.services.django.loadbalancer.server.port=8080"
