version: "3.4"
networks:
  proxynetwork:
    external: true
services:
  www:
    image: koromerzhin/django:3.9.0
    volumes:
      - ${PWD}/apps:/app
    networks:
      - proxynetwork
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.django.rule=Host(`django.traefik.me`)"
        - "traefik.http.routers.django-tls.tls.domains[0].main=django.traefik.me"
        - "traefik.http.routers.django-tls.tls.domains[0].sans=django-*.traefik.me"
        - "traefik.http.services.django.loadbalancer.server.port=8080"
