version: "3.4"
networks:
  proxynetwork:
    external: true
services:
  www:
    image: koromerzhin/django:3.9.0
    volumes:
      - ${PWD}/apps:/app
    networks:
      - proxynetwork
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.www-django.rule=Host(`django.lxc`, `www.django.lxc`)"
        - "traefik.http.middlewares.djangoredirectregex.redirectregex.regex=^http://django.lxc/(.*)"
        - "traefik.http.middlewares.djangoredirectregex.redirectregex.replacement=http://www.django.lxc/$${1}"
        - "traefik.http.routers.www-django.entrypoints=web"
        - "traefik.http.services.www-django.loadbalancer.server.port=8080"
