version: "3.4"
networks:
  proxylampy:
    external: true
  serverlampy:
    external: true
  net:
    driver: overlay
    attachable: true

services:
  www:
    image: koromerzhin/django:4.0.2
    command: >
      sh -c "pip -install -r requirements.txt && python manage.py runserver 0.0.0.0:8080"
    volumes:
      - ${PWD}/apps:/app
    networks:
      - serverlampy
      - proxylampy
    depends_on:
      - mariadb
      - mailhog
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.django.rule=Host(`django.traefik.me`)"
        - "traefik.http.routers.django-tls.tls.domains[0].main=django.traefik.me"
        - "traefik.http.routers.django.tls=true"
        - "traefik.http.services.django.loadbalancer.server.port=8080"
