version: "3.4"
networks:
  proxylampy:
    external: true
  serverlampy:
    external: true
services:
  www:
    image: python:3.14.0
    working_dir: /app
    command: >
      bash -c "source /.venv/bin/activate && pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8080"
    volumes:
      - ${PWD}/.venv:/.venv:delegated
      - ${PWD}/apps:/app:delegated
    depends_on:
      - mariadb
      - mailhog
    networks:
      - serverlampy
      - proxylampy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.django.rule=Host(`django.traefik.me`)"
        - "traefik.http.routers.django-tls.tls.domains[0].main=django.traefik.me"
        - "traefik.http.routers.django.tls=true"
        - "traefik.http.services.django.loadbalancer.server.port=8080"
